In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = DecisionTreeClassifier()
clf.fit(X, y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [4]:
importances = clf.feature_importances_
importances

array([0.75, 0.25])

In [3]:
np.isnan(X)

array([[False, False],
       [False, False],
       [False, False]])

In [113]:
import pandas as pd

df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [120]:
df_5 = df[['Pclass','Fare','Age','Sex', 'Survived']].dropna()
df_5.head()

Pclass     Fare   Age     Sex  Survived
0       3   7.2500  22.0    male         0
1       1  71.2833  38.0  female         1
2       3   7.9250  26.0  female         1
3       1  53.1000  35.0  female         1
4       3   8.0500  35.0    male         0

In [121]:
df_target = df_5['Survived']
df_target

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [122]:
df_4_clear = df_5[['Pclass','Fare','Age','Sex']].replace(('male', 'female'),(0,1))
df_4_clear

Pclass     Fare   Age  Sex
0         3   7.2500  22.0    0
1         1  71.2833  38.0    1
2         3   7.9250  26.0    1
3         1  53.1000  35.0    1
4         3   8.0500  35.0    0
..      ...      ...   ...  ...
885       3  29.1250  39.0    1
886       2  13.0000  27.0    0
887       1  30.0000  19.0    1
889       1  30.0000  26.0    0
890       3   7.7500  32.0    0

[714 rows x 4 columns]

In [123]:
X = np.array(df_4_clear)
y = np.array(df_target)
clf = DecisionTreeClassifier(random_state=241)
clf.fit(X, y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=241, splitter='best')

In [124]:
importances = clf.feature_importances_
importances

array([0.14751816, 0.29538468, 0.25658495, 0.30051221])