NUMPY

In [1]:
import numpy as np

In [3]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[ -8.31667933  -4.91001728   3.37963191 ...  -5.23847617  11.33977351
    6.2737121 ]
 [  9.07971142  -0.62660788   6.33077989 ...   5.33433636 -15.44876162
   -0.04771155]
 [ -8.21055008 -20.56285715  15.7847666  ...  -0.8900758   11.69187988
    3.60587876]
 ...
 [  7.93209393  -0.50434449   0.0626752  ... -20.84617074  -6.42642069
   -1.5276249 ]
 [ 12.01761706 -12.1983883    0.08810498 ...   2.86438669  -4.74829467
    3.12876585]
 [  3.49932686 -10.79309621  -5.05207797 ... -11.6586579   -1.06575195
   -0.4457783 ]]


In [4]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print(X_norm)

[[-0.90659866 -0.56242098  0.26350976 ... -0.65893178  0.98053291
   0.47703538]
 [ 0.78867394 -0.12859674  0.55930522 ...  0.40364888 -1.59408825
  -0.165717  ]
 [-0.8962564  -2.14774253  1.50688439 ... -0.2219122   1.01437353
   0.2057743 ]
 ...
 [ 0.67683899 -0.11621389 -0.06895095 ... -2.22752426 -0.72695947
  -0.31619225]
 [ 1.07497189 -1.30058809 -0.0664021  ...  0.1554159  -0.56567634
   0.15726221]
 [ 0.24486729 -1.15825993 -0.58160595 ... -1.30416793 -0.21175059
  -0.2061918 ]]


In [5]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [9]:
r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5], dtype=int64),)


In [11]:
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
AB = np.vstack((A, B))
print(AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


PANDAS

In [17]:
import pandas
data = pandas.read_csv('titanic.csv', index_col='PassengerId')
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [18]:
data['Pclass']

PassengerId
1      3
2      1
3      3
4      1
5      3
      ..
887    2
888    1
889    3
890    1
891    3
Name: Pclass, Length: 891, dtype: int64

In [19]:
data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

Задание №1
Какое количество мужчин и женщин ехало на корабле? В качестве ответа приведите два числа через пробел.

In [24]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

Задание №2 Какой части пассажиров удалось выжить? Посчитайте долю выживших пассажиров. Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.

In [48]:
round(data['Survived'].value_counts()[1]/len(data['Survived'])*100,2)

38.38

Задание №3 Какую долю пассажиры первого класса составляли среди всех пассажиров? Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.

In [46]:
round((data['Pclass']==1).sum()/len(data)*100,2)

24.24

Задание №4 Какого возраста были пассажиры? Посчитайте среднее и медиану возраста пассажиров. В качестве ответа приведите два числа через пробел.

In [51]:
data['Age'].mean()

29.69911764705882

In [52]:
data['Age'].median()

28.0

Задание №5 Коррелируют ли число братьев/сестер/супругов с числом родителей/детей? Посчитайте корреляцию Пирсона между признаками SibSp и Parch.

In [75]:
from scipy import stats
round(stats.pearsonr(data['SibSp'].values,data['Parch'].values)[0],2)

0.41

Задание №6 Какое самое популярное женское имя на корабле? Извлеките из полного имени пассажира (колонка Name) его личное имя (First Name). Это задание — типичный пример того, с чем сталкивается специалист по анализу данных. Данные очень разнородные и шумные, но из них требуется извлечь необходимую информацию. Попробуйте вручную разобрать несколько значений столбца Name и выработать правило для извлечения имен, а также разделения их на женские и мужские.

In [83]:
w_data = data[data['Sex']=='female'].reset_index()
w_data

PassengerId  Survived  Pclass  \
0              2         1       1   
1              3         1       3   
2              4         1       1   
3              9         1       3   
4             10         1       2   
..           ...       ...     ...   
309          881         1       2   
310          883         0       3   
311          886         0       3   
312          888         1       1   
313          889         0       3   

                                                  Name     Sex   Age  SibSp  \
0    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
1                               Heikkinen, Miss. Laina  female  26.0      0   
2         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
3    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
4                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
309       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
310                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
311               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
312                       Graham, Miss. Margaret Edith  female  19.0      0   
313           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   

     Parch            Ticket     Fare Cabin Embarked  
0        0          PC 17599  71.2833   C85        C  
1        0  STON/O2. 3101282   7.9250   NaN        S  
2        0            113803  53.1000  C123        S  
3        2            347742  11.1333   NaN        S  
4        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
309      1            230433  26.0000   NaN        S  
310      0              7552  10.5167   NaN        S  
311      5            382652  29.1250   NaN        Q  
312      0            112053  30.0000   B42        S  
313      2        W./C. 6607  23.4500   NaN        S  

[314 rows x 12 columns]

In [137]:
from collections import Counter
spisok_names = []
for i in range(len(w_data)):
    spisok_names.append(w_data['Name'][i].split(".")[-1])
slovar = Counter(spisok_names)
slovar

Counter({' John Bradley (Florence Briggs Thayer)': 1,
         ' Laina': 1,
         ' Jacques Heath (Lily May Peel)': 1,
         ' Oscar W (Elisabeth Vilhelmina Berg)': 1,
         ' Nicholas (Adele Achem)': 1,
         ' Marguerite Rut': 1,
         ' Elizabeth': 2,
         ' Hulda Amanda Adolfina': 1,
         ' (Mary D Kingcome) ': 1,
         ' Julius (Emelia Maria Vandemoortele)': 1,
         ' Fatima': 1,
         ' Anna "Annie"': 1,
         ' Torborg Danira': 1,
         ' Carl Oscar (Selma Augusta Emilia Johansson)': 1,
         ' Ellen "Nellie"': 2,
         ' William Augustus (Marie Eugenie)': 1,
         ' Mary Agatha': 1,
         ' Augusta Maria': 1,
         ' Jamila': 1,
         ' Johan (Johanna Persdotter Larsson)': 1,
         ' William John Robert (Dorothy Ann Wonnacott)': 1,
         ' Simonne Marie Anne Andree': 1,
         ' Margaret Delia': 1,
         ' Bridget': 1,
         ' Josef (Josefine Franchi)': 1,
         ' Henry Sleeper (Myna Haxtun)': 1,
        

In [134]:
def get_key(d, value):
    for k, v in d.items():
        if v == value:
            return k

In [139]:
get_key(slovar, max(slovar.values()))

' Mary'